services:
  - type: web
    name: praifahbot2
    env: python
    buildCommand: pyenv install 3.10.13 && pyenv global 3.10.13 && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
